# Generated by Django 6.0.4 on 2026-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField(unique=True)),
                ('text', models.TextField()),
                ('temperament', models.CharField(choices=[('Sangvinik', 'Sangvinik'), ('Xolerik', 'Xolerik'), ('Flegmatik', 'Flegmatik'), ('Melanxolik', 'Melanxolik')], max_length=20)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sangvinik_score', models.PositiveSmallIntegerField(default=0)),
                ('xolerik_score', models.PositiveSmallIntegerField(default=0)),
                ('flegmatik_score', models.PositiveSmallIntegerField(default=0)),
                ('melanxolik_score', models.PositiveSmallIntegerField(default=0)),
                ('dominant_temperament', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
